### PR TITLE
Add CI and tests

### PR DESCRIPTION
**Pull request by madsonic**
Tests cases are naive just to make sure CI works.

### CODE REVIEW

**Comment by madsonic** [comment]
using PR this time round since it was already done on my own fork

**Comment by damithc** [comment]
Enabled Travis.

**Comment by louislai** [comment]
would be good to include instructions on how to run the test in the `README`. Also i think its fine to enable ci on all branches?

**Comment by madsonic** [comment]
Ok will include the instructions
> would be good to include instructions on how to run the tests locally in the README. Also i think its fine to enable ci on all branches?

**Pull request merged**
