### PR TITLE
Fix regex

### PR DESCRIPTION
**Pull request by louislai**
Update regex to match new pr label format
Addresses #25

### CODE REVIEW

**Comment by madsonic** [comment]
1. Should we include student name as part of the pattern? 
2. LO number should allow double digits. i.e. W2.10a
3. more negative test should be included. If students forgot about the format they would likely submit a random string for the title. 
4. first 2 tests can use `regex.test.toBe(bool)` instead of exec

**Comment by louislai** [comment]
1. Student names are not always required. Not sure abt this semester, but in past semesters, sometimes you are required to submit a single PR as a group, which doesnt include the student names
2. I did not think it would reach 2-digit :p
3. if you can suggest some examples, would be nice :D
4. `exec` with comparison to `null` is used because that's closer to the actual usage in the code.

**Comment by madsonic** [comment]
1. OK this im not too sure. I am just reading off the instructions gave to the students
2. there are. if you look at wk 3, there's w3.10. Anyway it is very easy to make it a bit more robust
3. any english phrase would do. e.g. PR for week 3 LO, just 1 negative example to capture such impossibility.
4. should tests be testing against implementations? if they decide to return empty array next time this test would fail though.

**Comment by louislai** [comment]
4. Actually empty array would not be the same as null, so it would still be fine as it is.
2, 3 I 'll do some revisions to address them

**Comment by madsonic** [comment]
is there a typo? if empty array is not the same as `null` `toBeNull` would fail.

**Comment by louislai** [comment]
the first set of tests is checking for `not.toBeNull`

**Pull request merged**
